-- =====================================================================
-- Kalulu — Rediseño: sección "Ciencia ciudadana" (preguntas_ciencia_ciudadana)
-- SQL para pegar en el SQL Editor de Supabase (Dashboard > SQL Editor).
--
-- Idempotente: se puede correr las veces que haga falta sin romper nada.
-- No modifica ni elimina ninguna tabla existente. Reutiliza
-- public.is_admin() / public.admins ya creadas en etapa2_supabase_setup.sql
-- y sigue el mismo patrón de RLS que ya usan "noticias", "eventos" y
-- "recursos_destacados" en este proyecto.
--
-- Mientras esta tabla no exista (o esté vacía), la sección "Ciencia
-- ciudadana" del sitio sigue mostrando las mismas 4 preguntas que ya
-- tenía, cableadas como respaldo en assets/js/ciencia-preguntas.js — no
-- se rompe nada si todavía no se corre este archivo.
-- =====================================================================


-- =====================================================================
-- BLOQUE 1: tabla public.preguntas_ciencia_ciudadana
-- =====================================================================
create table if not exists public.preguntas_ciencia_ciudadana (
  id bigint generated by default as identity primary key,
  pregunta text not null,
  orden integer not null default 0,
  publicada boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

comment on table public.preguntas_ciencia_ciudadana is 'Preguntas editoriales de la sección "Ciencia ciudadana" de la Home. Visitantes solo ven las publicadas, ordenadas por "orden".';

create index if not exists preguntas_ciencia_ciudadana_orden_idx
  on public.preguntas_ciencia_ciudadana (publicada, orden);

alter table public.preguntas_ciencia_ciudadana enable row level security;


-- =====================================================================
-- BLOQUE 2: policies de public.preguntas_ciencia_ciudadana
-- =====================================================================
-- Cualquier visitante (incluso sin login) puede ver las preguntas publicadas.
drop policy if exists "Lectura publica preguntas publicadas" on public.preguntas_ciencia_ciudadana;
create policy "Lectura publica preguntas publicadas"
on public.preguntas_ciencia_ciudadana
for select
to anon, authenticated
using ( publicada = true );

-- Los admins ven TODAS las preguntas (publicadas y borradores) desde /admin.
drop policy if exists "Admins ven todas las preguntas" on public.preguntas_ciencia_ciudadana;
create policy "Admins ven todas las preguntas"
on public.preguntas_ciencia_ciudadana
for select
to authenticated
using ( public.is_admin() );

drop policy if exists "Admins crean preguntas" on public.preguntas_ciencia_ciudadana;
create policy "Admins crean preguntas"
on public.preguntas_ciencia_ciudadana
for insert
to authenticated
with check ( public.is_admin() );

drop policy if exists "Admins editan preguntas" on public.preguntas_ciencia_ciudadana;
create policy "Admins editan preguntas"
on public.preguntas_ciencia_ciudadana
for update
to authenticated
using ( public.is_admin() )
with check ( public.is_admin() );

drop policy if exists "Admins eliminan preguntas" on public.preguntas_ciencia_ciudadana;
create policy "Admins eliminan preguntas"
on public.preguntas_ciencia_ciudadana
for delete
to authenticated
using ( public.is_admin() );


-- =====================================================================
-- BLOQUE 3: seed conservador con las 4 preguntas reales ya existentes
-- en el sitio (no se inventa ninguna pregunta nueva). Solo se insertan
-- si la tabla está vacía, para no duplicar contenido en corridas futuras.
-- =====================================================================
insert into public.preguntas_ciencia_ciudadana (pregunta, publicada, orden)
select * from (values
  ('¿Debemos enseñar la cursiva desde el principio?', true, 1),
  ('¿Sirve usar una letra de cada color o es mejor todo en negro?', true, 2),
  ('¿Vale la pena usar textos con letras más espaciadas?', true, 3),
  ('¿Qué precursores de la lectura podemos enseñar en sala de 5?', true, 4)
) as datos (pregunta, publicada, orden)
where not exists (select 1 from public.preguntas_ciencia_ciudadana);


-- =====================================================================
-- BLOQUE 4 (opcional): verificación rápida
-- =====================================================================
select id, pregunta, publicada, orden from public.preguntas_ciencia_ciudadana order by orden;

select tablename, policyname, cmd, roles
from pg_policies
where tablename = 'preguntas_ciencia_ciudadana'
order by cmd;
