-- =====================================================================
-- Kalulu — Rediseño: página "/redesign/materiales/" (biblioteca de documentos)
-- SQL para pegar en el SQL Editor de Supabase (Dashboard > SQL Editor).
--
-- Idempotente: se puede correr las veces que haga falta sin romper nada.
-- No modifica ni elimina ninguna tabla existente. Reutiliza
-- public.is_admin() / public.admins ya creadas en etapa2_supabase_setup.sql
-- y sigue el mismo patrón de RLS que ya usan "noticias", "eventos",
-- "recursos_destacados", "preguntas_ciencia_ciudadana" y "equipo" en este
-- proyecto.
--
-- Mientras la tabla "materiales" no exista (o esté vacía), la página
-- pública /redesign/materiales/ muestra un catálogo de referencia con los
-- mismos títulos y categorías (ver assets/js/materiales-lista.js), pero
-- SIN botones "Ver"/"Descargar" funcionales: todavía no existe ningún
-- archivo real subido a Storage, así que esos botones se muestran
-- deshabilitados con la leyenda "Disponible próximamente" en vez de
-- apuntar a una URL inventada. En cuanto haya filas publicadas en esta
-- tabla con "archivo_path" real, Supabase pasa a ser la fuente de verdad
-- y esos botones empiezan a funcionar solos.
-- =====================================================================

create extension if not exists pgcrypto;


-- =====================================================================
-- BLOQUE 1: tabla public.materiales
-- =====================================================================
create table if not exists public.materiales (
  id bigint generated by default as identity primary key,
  titulo text not null,
  descripcion text,
  -- Categorías iniciales (ver también sección 9 del pedido original):
  -- "cuadernillos", "impresion", "guias", "juegos". El check no es una
  -- tabla separada de categorías a propósito (no hace falta todavía),
  -- pero sí evita cargar una categoría mal escrita por error.
  categoria text not null check (categoria in ('cuadernillos', 'impresion', 'guias', 'juegos')),
  -- Ruta DENTRO del bucket "materiales-archivos" (ej.
  -- "cuadernillos/cuadernillo-1.pdf"), no una URL pública completa: la URL
  -- pública se arma en el momento (bucket público) a partir de esta ruta,
  -- así que si el proyecto de Supabase cambia de URL en el futuro no hay
  -- que reescribir toda la tabla.
  archivo_path text,
  -- Nombre original del archivo (ej. "Cuadernillo 1.pdf"): se usa como
  -- atributo "download" para que, al descargar, el visitante vea un
  -- nombre prolijo en vez del path interno/UUID de Storage.
  nombre_archivo text,
  orden integer not null default 0,
  publicado boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

comment on table public.materiales is 'Biblioteca de documentos descargables de la página /materiales/. Visitantes solo ven los publicados, ordenados primero por categoria y despues por "orden". "archivo_path" es la ruta dentro del bucket "materiales-archivos", no una URL completa.';

create index if not exists materiales_orden_idx
  on public.materiales (publicado, categoria, orden);

alter table public.materiales enable row level security;


-- =====================================================================
-- BLOQUE 2: policies de public.materiales
-- =====================================================================
-- Cualquier visitante (incluso sin login) puede ver los materiales publicados.
drop policy if exists "Lectura publica materiales publicados" on public.materiales;
create policy "Lectura publica materiales publicados"
on public.materiales
for select
to anon, authenticated
using ( publicado = true );

-- Los admins ven TODOS los materiales (publicados y borrador) desde /admin.
drop policy if exists "Admins ven todos los materiales" on public.materiales;
create policy "Admins ven todos los materiales"
on public.materiales
for select
to authenticated
using ( public.is_admin() );

drop policy if exists "Admins crean materiales" on public.materiales;
create policy "Admins crean materiales"
on public.materiales
for insert
to authenticated
with check ( public.is_admin() );

drop policy if exists "Admins editan materiales" on public.materiales;
create policy "Admins editan materiales"
on public.materiales
for update
to authenticated
using ( public.is_admin() )
with check ( public.is_admin() );

drop policy if exists "Admins eliminan materiales" on public.materiales;
create policy "Admins eliminan materiales"
on public.materiales
for delete
to authenticated
using ( public.is_admin() );


-- =====================================================================
-- BLOQUE 3: bucket de Storage "materiales-archivos"
-- =====================================================================
-- Antes de correr este bloque, creá el bucket desde el Dashboard
-- (Storage > New bucket) con el nombre exacto "materiales-archivos",
-- marcado como público — mismo procedimiento que ya se usó para
-- "noticias-imagenes", "eventos-imagenes", "recursos-imagenes" y
-- "equipo-imagenes". Si el bucket no existe todavía, estas policies
-- quedan creadas sin efecto hasta que se cree (no fallan ni rompen nada).
--
-- Estructura sugerida dentro del bucket (coincide con "archivo_path"):
--   materiales-archivos/
--     cuadernillos/cuadernillo-1.pdf, cuadernillo-2.pdf, cuadernillo-3.pdf
--     impresion/cuadernillo-1-impresion.pdf, ...
--     guias/guia-pedagogica.pdf
--     juegos/bingo.pdf, revueltos.pdf

drop policy if exists "Lectura publica archivos materiales" on storage.objects;
create policy "Lectura publica archivos materiales"
on storage.objects
for select
to public
using ( bucket_id = 'materiales-archivos' );

drop policy if exists "Admins suben archivos materiales" on storage.objects;
create policy "Admins suben archivos materiales"
on storage.objects
for insert
to authenticated
with check (
  bucket_id = 'materiales-archivos'
  and public.is_admin()
);

drop policy if exists "Admins actualizan archivos materiales" on storage.objects;
create policy "Admins actualizan archivos materiales"
on storage.objects
for update
to authenticated
using ( bucket_id = 'materiales-archivos' and public.is_admin() )
with check ( bucket_id = 'materiales-archivos' and public.is_admin() );

drop policy if exists "Admins eliminan archivos materiales" on storage.objects;
create policy "Admins eliminan archivos materiales"
on storage.objects
for delete
to authenticated
using ( bucket_id = 'materiales-archivos' and public.is_admin() );


-- =====================================================================
-- BLOQUE 4: tabla singleton public.materiales_config (WhatsApp / contacto)
-- =====================================================================
-- Una sola fila (id = 1), mismo patrón que "home_config": permite cambiar
-- el link de la comunidad de WhatsApp o el email de contacto desde
-- /admin, sin tocar código. Se crea vacía a propósito (whatsapp_url y
-- contacto_email en NULL) porque hoy no existe ningún link real de
-- WhatsApp en el proyecto (se buscó en todo el sitio, tanto en
-- /redesign como en producción, y no aparece en ningún archivo) — no se
-- inventa una URL. Mientras esta fila no tenga whatsapp_url cargado, la
-- página pública muestra el texto del CTA sin convertirlo en un enlace
-- roto (ver assets/js/materiales-lista.js).
create table if not exists public.materiales_config (
  id smallint primary key default 1,
  whatsapp_url text,
  contacto_email text,
  updated_at timestamptz not null default now(),
  constraint materiales_config_singleton check (id = 1)
);

comment on table public.materiales_config is 'Fila única (id=1) con datos configurables de la página /materiales/: link de la comunidad de WhatsApp y email de contacto. Editable desde /admin sin tocar código.';

alter table public.materiales_config enable row level security;

drop policy if exists "Lectura publica materiales_config" on public.materiales_config;
create policy "Lectura publica materiales_config"
on public.materiales_config
for select
to anon, authenticated
using ( true );

drop policy if exists "Admins editan materiales_config" on public.materiales_config;
create policy "Admins editan materiales_config"
on public.materiales_config
for update
to authenticated
using ( public.is_admin() )
with check ( public.is_admin() );

drop policy if exists "Admins insertan materiales_config" on public.materiales_config;
create policy "Admins insertan materiales_config"
on public.materiales_config
for insert
to authenticated
with check ( public.is_admin() );

-- Fila única, vacía (sin inventar ninguna URL ni email).
insert into public.materiales_config (id, whatsapp_url, contacto_email)
select 1, null, null
where not exists (select 1 from public.materiales_config where id = 1);


-- =====================================================================
-- BLOQUE 5: catálogo inicial (sin archivo todavía — ver nota arriba)
-- =====================================================================
-- Se cargan los 9 documentos pedidos, TODOS con archivo_path = NULL y
-- publicado = false: son un catálogo de referencia, no materiales reales
-- todavía disponibles. Un admin sube el PDF real de cada uno desde
-- /admin (pestaña "Materiales" > Editar > subir archivo) y recién ahí
-- los publica; en ese momento la página pública empieza a mostrar el
-- botón "Ver"/"Descargar" funcional para ese documento (ver también el
-- punto 5 del informe final: pasos para subir/migrar los documentos).
insert into public.materiales (titulo, descripcion, categoria, archivo_path, nombre_archivo, publicado, orden)
select * from (values
  ('Cuadernillo 1', null::text, 'cuadernillos', null::text, null::text, false, 1),
  ('Cuadernillo 2', null::text, 'cuadernillos', null::text, null::text, false, 2),
  ('Cuadernillo 3', null::text, 'cuadernillos', null::text, null::text, false, 3),
  ('Cuadernillo 1 — impresión', null::text, 'impresion', null::text, null::text, false, 1),
  ('Cuadernillo 2 — impresión', null::text, 'impresion', null::text, null::text, false, 2),
  ('Cuadernillo 3 — impresión', null::text, 'impresion', null::text, null::text, false, 3),
  ('Guía pedagógica', null::text, 'guias', null::text, null::text, false, 1),
  ('Bingo', null::text, 'juegos', null::text, null::text, false, 1),
  ('Revueltos', null::text, 'juegos', null::text, null::text, false, 2)
) as datos (titulo, descripcion, categoria, archivo_path, nombre_archivo, publicado, orden)
where not exists (select 1 from public.materiales);


-- =====================================================================
-- BLOQUE 6 (opcional): verificación rápida
-- =====================================================================
select id, titulo, categoria, orden, publicado, archivo_path from public.materiales order by categoria, orden;

select * from public.materiales_config;

select tablename, policyname, cmd, roles
from pg_policies
where tablename in ('materiales', 'materiales_config')
order by tablename, cmd;

select policyname, cmd, roles
from pg_policies
where tablename = 'objects' and schemaname = 'storage' and policyname ilike '%materiales%'
order by cmd;
