-- =====================================================================
-- Kalulu — Rediseño: sección "Quiénes somos" (equipo)
-- SQL para pegar en el SQL Editor de Supabase (Dashboard > SQL Editor).
--
-- Idempotente: se puede correr las veces que haga falta sin romper nada.
-- No modifica ni elimina ninguna tabla existente. Reutiliza
-- public.is_admin() / public.admins ya creadas en etapa2_supabase_setup.sql
-- y sigue el mismo patrón de RLS que ya usan "noticias", "eventos",
-- "recursos_destacados" y "preguntas_ciencia_ciudadana" en este proyecto.
--
-- Mientras esta tabla no exista (o esté vacía), la sección "Quiénes
-- somos" del sitio sigue mostrando los 8 integrantes reales ya
-- cableados como respaldo en el HTML y en assets/js/equipo.js, con sus
-- fotos locales actuales — no se pierde ninguna foto ni se rompe nada
-- si todavía no se corre este archivo.
-- =====================================================================

-- pgcrypto ya viene habilitado por defecto en todo proyecto de Supabase;
-- este "create extension" es solo una red de seguridad idempotente.
create extension if not exists pgcrypto;


-- =====================================================================
-- BLOQUE 1: tabla public.equipo
-- =====================================================================
create table if not exists public.equipo (
  id bigint generated by default as identity primary key,
  nombre text not null,
  descripcion text,
  imagen_url text,
  link text,
  orden integer not null default 0,
  publicada boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

comment on table public.equipo is 'Integrantes del equipo mostrados en "Quiénes somos". Visitantes solo ven los publicados, ordenados por "orden". imagen_url puede quedar en null mientras se migran las fotos: el frontend usa la foto local existente como respaldo en ese caso.';

create index if not exists equipo_orden_idx
  on public.equipo (publicada, orden);

alter table public.equipo enable row level security;


-- =====================================================================
-- BLOQUE 2: policies de public.equipo
-- =====================================================================
-- Cualquier visitante (incluso sin login) puede ver a los integrantes publicados.
drop policy if exists "Lectura publica equipo publicado" on public.equipo;
create policy "Lectura publica equipo publicado"
on public.equipo
for select
to anon, authenticated
using ( publicada = true );

-- Los admins ven a TODO el equipo (publicado y borrador) desde /admin.
drop policy if exists "Admins ven todo el equipo" on public.equipo;
create policy "Admins ven todo el equipo"
on public.equipo
for select
to authenticated
using ( public.is_admin() );

drop policy if exists "Admins crean integrantes" on public.equipo;
create policy "Admins crean integrantes"
on public.equipo
for insert
to authenticated
with check ( public.is_admin() );

drop policy if exists "Admins editan integrantes" on public.equipo;
create policy "Admins editan integrantes"
on public.equipo
for update
to authenticated
using ( public.is_admin() )
with check ( public.is_admin() );

drop policy if exists "Admins eliminan integrantes" on public.equipo;
create policy "Admins eliminan integrantes"
on public.equipo
for delete
to authenticated
using ( public.is_admin() );


-- =====================================================================
-- BLOQUE 3: bucket de Storage "equipo-imagenes"
-- =====================================================================
-- Antes de correr este bloque, creá el bucket desde el Dashboard
-- (Storage > New bucket) con el nombre exacto "equipo-imagenes",
-- marcado como público — mismo procedimiento que ya se usó para
-- "noticias-imagenes", "eventos-imagenes" y "recursos-imagenes".
-- Si el bucket no existe todavía, estas policies quedan creadas sin
-- efecto hasta que se cree (no fallan ni rompen nada).

drop policy if exists "Lectura publica imagenes equipo" on storage.objects;
create policy "Lectura publica imagenes equipo"
on storage.objects
for select
to public
using ( bucket_id = 'equipo-imagenes' );

drop policy if exists "Admins suben imagenes equipo" on storage.objects;
create policy "Admins suben imagenes equipo"
on storage.objects
for insert
to authenticated
with check (
  bucket_id = 'equipo-imagenes'
  and public.is_admin()
);

drop policy if exists "Admins actualizan imagenes equipo" on storage.objects;
create policy "Admins actualizan imagenes equipo"
on storage.objects
for update
to authenticated
using ( bucket_id = 'equipo-imagenes' and public.is_admin() )
with check ( bucket_id = 'equipo-imagenes' and public.is_admin() );

drop policy if exists "Admins eliminan imagenes equipo" on storage.objects;
create policy "Admins eliminan imagenes equipo"
on storage.objects
for delete
to authenticated
using ( bucket_id = 'equipo-imagenes' and public.is_admin() );


-- =====================================================================
-- BLOQUE 4: seed con los 8 integrantes reales ya existentes en el sitio
-- (nombres y cargos exactamente como figuran hoy — no se inventa ni se
-- omite a nadie). imagen_url se deja en NULL a propósito: todavía no
-- hay una URL pública de Storage para estas fotos, y el frontend
-- (assets/js/equipo.js) ya sabe usar la foto local existente como
-- respaldo mientras tanto. Un admin puede subir cada foto a Storage
-- desde /admin cuando quiera, sin perder la foto actual en el ínterin.
-- =====================================================================
insert into public.equipo (nombre, descripcion, imagen_url, publicada, orden)
select * from (values
  ('Melina Vladisauskas', 'Dra. en Biología, Postdoc en Excello Lab - Collège de France', null::text, true, 1),
  ('Julia Hermida', 'Dra. en Psicología UBA, Profesora adjunta en UNAHUR, Investigadora Asistente en CONICET', null::text, true, 2),
  ('Cassandra Potier Watkins', 'Investigadora en Neurociencia Cognitiva y Educación (Collège de France), Fundadora de Excello', null::text, true, 3),
  ('Andrés Rieznik', 'Dr. en Física, Profesor full time en UTDT, Comunicador científico', null::text, true, 4),
  ('Stanislas Dehaene', 'Investigador en Neurociencia Cognitiva, Prof. en Collège de France, Dir. de NeuroSpin (INSERM-CEA)', null::text, true, 5),
  ('Agripina Sanchez Menta', 'Docente de primaria y Psicopedagoga', null::text, true, 6),
  ('Romina Curto', 'Docente y estudiante de psicopedagogía', null::text, true, 7),
  ('Marie Lubineau', 'Doctora en Ciencias Cognitivas, Postdoctorado en Excello Lab - Collège de France', null::text, true, 8)
) as datos (nombre, descripcion, imagen_url, publicada, orden)
where not exists (select 1 from public.equipo);


-- =====================================================================
-- BLOQUE 5 (opcional): verificación rápida
-- =====================================================================
select id, nombre, publicada, orden, imagen_url from public.equipo order by orden;

select tablename, policyname, cmd, roles
from pg_policies
where tablename = 'equipo'
order by cmd;

select policyname, cmd, roles
from pg_policies
where tablename = 'objects' and schemaname = 'storage' and policyname ilike '%equipo%'
order by cmd;
